### ISSUE TITLE
[feat] 인터벌 리프레시, 수정, 삭제 구현

### ISSUE THREAD

**Issue by annapo99** [TEAM-ALOM/interest-iOS#24]
## 👀 Issue

View 보다는 로직이 많이 복잡할 텐데, 특히 IntervalScreen(부모) AddIntervalScreen(자식1), IntervalListScreen(자식2) 간의 ViewModel 로직을 고민해보면서 작성하는 것이 좋아보입니다. Todo에 있는 것들을 차근차근 진행하시면 될 것 같아요. 화요일(1/9)에 회의 때 말했던 작업은 미루어졌습니다.

전부 다 안해도 되고, 할수있는 만큼만 진행하면 됩니다!

### ✅ Todo
- [ ] AddIntervalScreen 에서 저장을 누르면 interval이 save되고 Sheet가 dismiss되고 뷰모델의 fetchIntervals가 호출되면서 ListScreen에 있는 Interval Cell들이 리프레시 되어야 함
- [ ] 수정, 삭제가 가능해야함. 기존의 EditIntervalScreen은 이제 사용하지 않고 AddIntervalScreen으로 생성과 수정을 통합해야함
- [ ] 수정과 삭제 이후에 모든 Cell들은 refresh가 되어야 함. 바텀시트가 내려가면 interval 들은 refresh 되어야 함
