### ISSUE TITLE
[feat] Watch와 iOS 연동 시작

### ISSUE THREAD

**Issue by annapo99** [TEAM-ALOM/interest-iOS#25]
## 👀 Issue

모든 것을 다할 수는 없지만, 연결의 시작 점을 고민하는 것이 핵심입니다. iOS와 Watch는 양쪽 모두에서 트리거 될 수 있어야 하고, Watch 독립적으로 사용이 가능해야합니다. 또한 iOS 독립적으로도 사용가능해야합니다. 그리고 둘다 동시에 사용이 가능해야 합니다. iOS로 동작하고 있다가 중간에 Watch 앱이 실행되는 상황과 Watch앱이 동작하고 있다가 중간데 iOS 앱이 실행되는 상황이 있을 수 있습니다. 다양한 케이스들이 있을 것이고 모든 케이스를 어떻게 하면 잘 관리할 수 있을지, 적절한 UseCase 단으로 고민하는 것이 좋을 것 같아요. 

우선, iOS와 Watch 둘다 켜져있는 상황부터 시작하면 좋을 것 같아요.

### ✅ Todo
- [ ] iOS 타이머 시작 버튼을 누르면 iOS가 실행되고 Watch도 실행 됩니다.
- [ ] Watch 타이머 시작 버튼을 누르면 Watch가 실행되고 iOS도 실행 됩니다.
- [ ] iOS 타이머 일시 정지를 누르면 iOS가 멈추고 Watch 도 멈춥니다.
- [ ] Watch 타이머 일시 정지를 누르면 Watch가 멈추고 iOS도 멈춥니다.

**Comment by annapo99** [comment]
@ShapeKim98  healthKit 작업도 해주시면 좋을 것 같아요. 저희 앱의 스펙 상 칼로리와 심박수를 가져와야 합니다.
