### ISSUE TITLE
[feat] 운동중 & 버닝중 기능 구현

### ISSUE THREAD

**Issue by annapo99** [TEAM-ALOM/interest-iOS#27]
## 👀 Issue

UI와 ViewModel은 무조건 워치와 아이폰 통합적으로 개발되어야 합니다. 통합이라는 뜻은 항상 같은 flow를 사용될 것을 염두에 두고 개발이 되어야 한다는 뜻입니다. 그리고, ViewModel의 로직은 너무 어렵다 싶으면 pr을 미리 날려서 도움을 요청하는 것도 좋은 방법이라고 생각합니다. 항상 혼자고민하는 것보다 여럿이서 고민하는 것이 모두에게 좋은 학습 기회가 된다고 생각합니다.

ViewModel의 로직은 타이머 로직 정도가 들어가면 좋을 것 같고, 가능하다면 실시간으로 저장되는 로직도 추가되면 좋을 것 같습니다. 그리고 실제로 운동중 기능을 개발하며 Entity나 DTO(PersistentModel)의 수정이 필요한 부분을 가장 먼저 발견하실수도 있을텐데 이럴 경우에 '내가 수정해도 될까' 하시지말고 그냥 수정하고 추후에 pr을 통해서 리뷰를 받는 것으로 하면 좋을 것 같아요. PersistentModel을 수정할 경우 앱을 삭제했다가(기존 모델로 저장되어있는 것들을 지워야할 수 있음) 빌드 하면 오류를 없앨 수 있습니다.

### ✅ Todo
- [x] 아이폰의 운동중, 버닝중 UI 구현
- [x] 애플워치의 운동중, 버닝중 UI 구현
- [x] ViewModel 로직 처리 타이머, 버닝 중 <-> 운동 중 자동으로 왔다갔다 처리, 등등 자잘한 것들(잘 모르겠어요.. 알잘딱갈센..?)
