### ISSUE TITLE
[feat] Interval Add, Edit, Delete 의 상세 구현

### ISSUE THREAD

**Issue by annapo99** [TEAM-ALOM/interest-iOS#36]
## 👀 Issue

저희는 지금 Interval Add와 Interval Edit을 동일한 ViewModel과 Screen으로 구현하였는데요, 분리가 필요합니다.

Feature 레이어 (필수)
- AddIntervalScreen, AddIntervalViewModel
- EditIntervalScreen, EditIntervalViewModel

Presentation 레이어 (예시, 선택 사항)
- AddIntervalView, BurningTypePickerView ... 
- EditIntervalView

Presentation의 레이어는 ViewModel을 직접 참조하지 않고, Domain 레이어의 Entity 만을 사용하여 구현하도록 합니다.

```swift
public struct AddIntervalView: View {
    @Binding var intervalEntity: IntervalEntity
...
}
```
이런식으로 Entity를 참조하여 구현 합니다. UseCase를 사용하지 않습니다. 그리고 공통적인 사항으로 이제 Item은 사용하지 않고, Entity 만을 사용할 예정이니깐 그렇게 작성해주세요. ObjectMapper 이런거 안쓸 예정입니다. 기존에는 IntervalDTO, IntevalEntity, IntervalModel 이었는데 (Model을 없앤다는 뜻)

### ✅ Todo
- [x] Interval Add 화면 및 ViewModel 구현
- [x] Interval Edit 화면 및 ViewModel 구현
- [x] Interval Delete 로직 구현
