### ISSUE TITLE
[feat] 애플워치 UI 디테일

### ISSUE THREAD

**Issue by YugyeongChoi** [TEAM-ALOM/interest-iOS#47]
## 👀 Issue
애플워치 UI 디테일 변경

### ✅ Todo
- [ ] 타이머 설정하면 알아서 닫히게 구현
- [x] 애플워치 운동 선택 구현
- [x] 애플워치 UI 디테일 수정
